### ISSUE TITLE
Cleanup local_content for a specific room

### ISSUE THREAD

**Issue by rajil** [mserajnik/synapse-purge#3]
Hello,

I want to clean up local_content for a specific room. Is that possible?

I am running a few bridges, and keep collecting media which i dont want. I want to retain the media for the room i host, however want to delete the media coming through the bridges. Thus, deleting media for a specific room will be very helpful.

Thanks

**Comment by imtbl** [comment]
Hey, we currently don't have any plans to add support for purging specific rooms. We mainly made this tool for our own use and released it to the public because we thought it might be useful to others.

That said, contributions are welcome. I could see having a setting with a list of IDs to purge, for example.

We are currently just selecting all the room IDs, so this should be rather easy to expand: https://github.com/imtbl/synapse-purge/blob/37c82edf5a7fd136cf77dfdfef947fb7627bb389/synapse-purge.py#L215

**Comment by mserajnik** [comment]
Closed due to project relaunch, see README.
